
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/josemanuelmartinfuentezuelas/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 5.15.117-19680-g54e910f94133 - x86_64
...
